### ISSUE TITLE
Add Resources Package

### ISSUE THREAD

**Issue by tapsshore** [chetachiezikeuzor/CapstoneProjectSpring2022#33]
There is need to add the resources package as well as the application.properties/yml file to add database configurations inorder to start the applivation. I can do that if its not already done

**Comment by chetachiezikeuzor** [comment]
Yes you will need to update our application.properties file. I have provided a template in the README.

**Comment by tapsshore** [comment]
kindly assign the issues to me

**Comment by chetachiezikeuzor** [comment]
Sorry to say but this project is for my class assignment. But you are free to create a copy of your own!

**Comment by tapsshore** [comment]
Oh okay, sorry about that, i thought it is just an open-source project. Sorry to disturb there

**Comment by chetachiezikeuzor** [comment]
You're fine! Please let me know if you're in need of anything else. Thanks!
